### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by altugkarakurt** [altugkarakurt/EnergyEfficientCapacityManagement#1]
**Tests:**
- [x] Shortest Queue First Scheduling
- [x] Longest Queue First Scheduling
- [x] Random Scheduling
- [X] Constant Process Times
- [X] Poisson Process Times
- [X] Homogeneous Arrivals
- [ ] Non-homogeneous Arrivals
- [X] Single Server in the Environment
- [x] Multiple Servers in the Environment

**Implementations:**
- [ ] We need to get / create lambda lists for Nonhomogeneous Poisson Arrivals
- [ ] Monitor class for monitoring the time packages spend in the server / queue.
- [ ] Server states and their monitoring class. This class should be responsible of keeping track of number of idle/free/fully busy servers. The package routing should be moved to there from Simulator and it should switch on/off servers. The hysteresis effect will be embedded to this class.
- [x] New stop_simulation() function to Simulator. The simulation should continue until the queue is emptied and so on. When run_time is reached without exceeding package_limit, PackageGenerator should be killed.
